#!/usr/bin/env bash
source "$(dirname "${0}")/common.sh"
set -ueo pipefail

hosts_dir="hosts"

if [ "${use_examples:-false}" == "true" ]; then
  hosts_dir="examples"
fi

hosts=$(
  find "${hosts_dir}" \
    -type f \
    -name '*.yaml' \
    -and -not \( -name 'example.yaml' -or -name 'network.yaml' \) \
    | sed -e 's|^hosts/||' -e 's|^examples/||' -e 's|\.yaml$||'
)

exports=$(
  find templates/exports \
    -type f \
    \( -name '*.rsc.t' -or -name '*.scr.t' \) \
    | sed -e 's|^templates/exports/||' -e 's|\.rsc.t$||' -e 's|\.scr.t$||'
)

echo "${hosts[@]}" | while read -r host; do
  echo "${exports[@]}" | while read -r export; do
    echo "${host}:${export}"
  done
done | fzf --filter "${1:-:}"
