#!/usr/bin/env bash
# shellcheck disable=SC2154 # Some variables are managed in lib.sh
set -ueo pipefail

source "$(dirname "${0}")/common.sh"
source "$(dirname "${0}")/lib.sh"

info "${host}:${export}.rsc"

if [[ "${use_examples:-false}" == "true" ]]; then
  fatal "Cannot upload examples/ exports to hosts"
fi

if [[ ! -f "${export_file}.${export_ext}" ]]; then
  fatal "Cannot find ${export_file}.${export_ext} to upload"
fi

sub-note "Checking host is alive..."
if ! ping -4An -w1 -l3 -c3 "${host}" > /dev/null 2>&1; then
  fatal "Cannot find host ${host}"
fi

sub-note "Uploading ${export}.rsc file..."
if ! scp -q "${export_file}.${export_ext}" "${host}:${export}.rsc"; then
  error "Upload failed"
fi
